Lattice 1726
openlattice/transporter pull request #2
Opened 2019-01-18 22:21 UTC by jokedurnez

We got a basic service that has a scheduled job that can read the database.

2019-01-21 18:36 UTC, geekbeast requested changes

2019-01-21 18:36 UTC, geekbeast commented on build.gradle
> +/////////// ANYTHING BELOW SHOULD BE UNCOMMENTED AS SOON AS GIT STUFF ABOVE WORKS /////////
?

2019-01-21 18:36 UTC, geekbeast commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-bin.zip
Should switch to 4.10.3

2019-01-21 18:36 UTC, geekbeast commented on src/main/resources/rhizome.yaml
> +    username: "jokedurnez"
Use oltest so it works on other people's machines without configuration.

2019-02-01 20:50 UTC, jokedurnez commented
@geekbeast solved your comments.

2019-04-26 22:03 UTC, closed without merging